-- ===========
-- SECUENCIA
-- ===========
CREATE SEQUENCE AUDIT_SEQUENCE
START WITH 1
INCREMENT BY 1;

-- ==========
-- TRIGGER
-- ==========
create or replace 
trigger TR_SEQ_AUDITORIA 
BEFORE INSERT
ON AUDITORIA
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT AUDIT_SEQUENCE.nextval INTO :NEW.CODSEGUIMIENTO FROM dual;
END;
/