/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2014-07-18 00:20:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Carga.jsp", Long.valueOf(1405637613530L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/normalize.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/estilos.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.6.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-yui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-replace.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"js/Forum_400.font.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/tms-0.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/tms_presets.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/atooltip.jquery.js\"></script> ");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("   body { Background: transparent; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\t\t<article id=\"content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider_bg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slider\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"items\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/img1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"banner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Pizza<span>Suprema</span></strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Plato del Dia</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Famosa combinacion de peperoni,<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcarne de res, champignones, pimientos verdes, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcebolla y queso mozzarella. </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/img2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"banner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Lasaña<span>Florentina</span></strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Plato del Dia</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Deliciosa combinacion <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tde salsa blanca, espinaca y jamon.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/img3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"banner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Pesto<span>Chicken</span></strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Nuevo Plato</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Exquisita combinacion <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tpechuga de pollo rociados con pesto, queso mozzarella\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ty queso parmesano.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"wrap\">\r\n");
      out.write("\t\t\t\t\t\t<section class=\"cols\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>Sobre<span> Nosotros</span></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure><img src=\"images/page1_img2.jpg\" alt=\"\" ></figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"pad_bot1\"> Durante más de 50 años, millones de aficionados como usted han inspirado a Pizza Ravioli para hacer la mejor pizza durante los momentos favoritos de la vida.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"button1\">Leer Mas</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t<section class=\"cols pad_left1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>Nuestra<span> Mision</span></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure><img src=\"images/page1_img3.jpg\" alt=\"\" ></figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"pad_bot1\">Brindar productos de alta calidad y atención personalizada a cada uno de nuestros invitados a fin de lograr la fidelidad de ellos, con un equipo altamente motivado y capacitado.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"button1\">Leer Mas</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t<section class=\"cols pad_left1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>Nuestra<span> Vision</span></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<figure><img src=\"images/page1_img1.jpg\" alt=\"\" ></figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"pad_bot1\">\"Ser la pizzeria más rentables del Perú respetando fielmente los valores que nos comprometen, trasladándolos a nuestros clientes, proveedores y a la sociedad.\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"button1\">Leer Mas</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write("<script type=\"text/javascript\"> Cufon.now(); </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
